/******************************************************************************/
/****                               Domains                                ****/
/******************************************************************************/



/******************************************************************************/
/****                              Exceptions                              ****/
/******************************************************************************/

/******************************************************************************/
/****                              Procedures                              ****/
/******************************************************************************/

SET TERM ^ ;

SET TERM ; ^



/******************************************************************************/
/****                           Tables and Views                           ****/
/******************************************************************************/

CREATE TABLE ACOES (
    ID_ACAO INTEGER GENERATED BY DEFAULT AS IDENTITY,
    NOME VARCHAR(100) CHARACTER SET UTF8 NOT NULL,
    DESCRICAO VARCHAR(200) CHARACTER SET UTF8);


CREATE TABLE ATIVOS (
    ID_ATIVO INTEGER GENERATED BY DEFAULT AS IDENTITY,
    DESCRICAO VARCHAR(100) CHARACTER SET UTF8 NOT NULL,
    NUMERO_SERIE VARCHAR(50) CHARACTER SET UTF8,
    STATUS VARCHAR(20) CHARACTER SET UTF8,
    ID_CLIENTE_PROPRIETARIO INTEGER);


CREATE TABLE ATIVOS_CONTRATOS (
    ID_CONTRATO INTEGER NOT NULL,
    ID_ATIVO INTEGER NOT NULL,
    DATA_ENTREGA DATE,
    DATA_DEVOLUCAO DATE);


CREATE TABLE AUDITORIA (
    ID_LOG INTEGER GENERATED BY DEFAULT AS IDENTITY,
    ID_USUARIO INTEGER,
    ID_ACAO INTEGER,
    ENTIDADE VARCHAR(50) CHARACTER SET UTF8,
    ID_ENTIDADE INTEGER,
    DATA_HORA TIMESTAMP);


CREATE TABLE CLIENTES (
    ID_CLIENTE INTEGER GENERATED BY DEFAULT AS IDENTITY,
    TIPO_PESSOA CHAR(1) CHARACTER SET UTF8,
    NOME_RAZAO VARCHAR(100) CHARACTER SET UTF8 NOT NULL,
    NOME_FANTASIA VARCHAR(100) CHARACTER SET UTF8,
    CPF_CNPJ VARCHAR(20) CHARACTER SET UTF8 NOT NULL,
    IE VARCHAR(20) CHARACTER SET UTF8,
    RG VARCHAR(20) CHARACTER SET UTF8,
    DATA_NASCIMENTO DATE,
    TELEFONE VARCHAR(20) CHARACTER SET UTF8,
    EMAIL VARCHAR(100) CHARACTER SET UTF8,
    ENDERECO VARCHAR(100) CHARACTER SET UTF8,
    NUMERO VARCHAR(10) CHARACTER SET UTF8,
    COMPLEMENTO VARCHAR(50) CHARACTER SET UTF8,
    BAIRRO VARCHAR(60) CHARACTER SET UTF8,
    CEP VARCHAR(10) CHARACTER SET UTF8,
    MUNICIPIO VARCHAR(60) CHARACTER SET UTF8,
    UF CHAR(2) CHARACTER SET UTF8,
    CODIGO_MUNICIPIO INTEGER,
    PAIS VARCHAR(60) CHARACTER SET UTF8,
    CODIGO_PAIS INTEGER);


CREATE TABLE CONTRATOS (
    ID_CONTRATO INTEGER GENERATED BY DEFAULT AS IDENTITY,
    ID_CLIENTE INTEGER NOT NULL,
    DATA_INICIO DATE NOT NULL,
    DATA_FIM DATE,
    VALOR_MENSAL DECIMAL(15,2),
    OBSERVACOES BLOB SUB_TYPE 1 SEGMENT SIZE 80 CHARACTER SET UTF8,
    ID_STATUS INTEGER);


CREATE TABLE PAGAMENTOS (
    ID_PAGAMENTO INTEGER GENERATED BY DEFAULT AS IDENTITY,
    ID_CONTRATO INTEGER NOT NULL,
    DATA_VENCIMENTO DATE NOT NULL,
    DATA_PAGAMENTO DATE,
    VALOR_PAGO DECIMAL(15,2),
    STATUS_PAGAMENTO VARCHAR(20) CHARACTER SET UTF8);


CREATE TABLE PERFIS (
    ID_PERFIL INTEGER GENERATED BY DEFAULT AS IDENTITY,
    NOME VARCHAR(50) CHARACTER SET UTF8 NOT NULL,
    DESCRICAO VARCHAR(200) CHARACTER SET UTF8);


CREATE TABLE PERMISSOES (
    ID_PERFIL INTEGER NOT NULL,
    NOME_TELA VARCHAR(100) CHARACTER SET UTF8 NOT NULL,
    PODE_ACESSAR BOOLEAN DEFAULT FALSE);


CREATE TABLE STATUS_CONTRATO (
    ID_STATUS INTEGER GENERATED BY DEFAULT AS IDENTITY,
    NOME VARCHAR(50) CHARACTER SET UTF8 NOT NULL,
    DESCRICAO VARCHAR(200) CHARACTER SET UTF8,
    ATIVO BOOLEAN DEFAULT TRUE);


CREATE TABLE USUARIOS (
    ID_USUARIO INTEGER GENERATED BY DEFAULT AS IDENTITY,
    NOME VARCHAR(100) CHARACTER SET UTF8 NOT NULL,
    EMAIL VARCHAR(100) CHARACTER SET UTF8 NOT NULL,
    SENHA VARCHAR(100) CHARACTER SET UTF8 NOT NULL,
    ID_PERFIL INTEGER NOT NULL);




/******************************************************************************/
/****                             Primary keys                             ****/
/******************************************************************************/


ALTER TABLE ACOES ADD PRIMARY KEY (ID_ACAO);
ALTER TABLE ATIVOS ADD PRIMARY KEY (ID_ATIVO);
ALTER TABLE ATIVOS_CONTRATOS ADD PRIMARY KEY (ID_CONTRATO, ID_ATIVO);
ALTER TABLE AUDITORIA ADD PRIMARY KEY (ID_LOG);
ALTER TABLE CLIENTES ADD PRIMARY KEY (ID_CLIENTE);
ALTER TABLE CONTRATOS ADD PRIMARY KEY (ID_CONTRATO);
ALTER TABLE PAGAMENTOS ADD PRIMARY KEY (ID_PAGAMENTO);
ALTER TABLE PERFIS ADD PRIMARY KEY (ID_PERFIL);
ALTER TABLE PERMISSOES ADD PRIMARY KEY (ID_PERFIL, NOME_TELA);
ALTER TABLE STATUS_CONTRATO ADD PRIMARY KEY (ID_STATUS);
ALTER TABLE USUARIOS ADD PRIMARY KEY (ID_USUARIO);

/******************************************************************************/
/****                          Unique constraints                          ****/
/******************************************************************************/



/******************************************************************************/
/****                             Foreign keys                             ****/
/******************************************************************************/


ALTER TABLE ATIVOS ADD FOREIGN KEY (ID_CLIENTE_PROPRIETARIO) REFERENCES CLIENTES (ID_CLIENTE);
ALTER TABLE ATIVOS_CONTRATOS ADD FOREIGN KEY (ID_CONTRATO) REFERENCES CONTRATOS (ID_CONTRATO);
ALTER TABLE ATIVOS_CONTRATOS ADD FOREIGN KEY (ID_ATIVO) REFERENCES ATIVOS (ID_ATIVO);
ALTER TABLE AUDITORIA ADD FOREIGN KEY (ID_USUARIO) REFERENCES USUARIOS (ID_USUARIO);
ALTER TABLE AUDITORIA ADD FOREIGN KEY (ID_ACAO) REFERENCES ACOES (ID_ACAO);
ALTER TABLE CONTRATOS ADD FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTES (ID_CLIENTE);
ALTER TABLE CONTRATOS ADD FOREIGN KEY (ID_STATUS) REFERENCES STATUS_CONTRATO (ID_STATUS);
ALTER TABLE PAGAMENTOS ADD FOREIGN KEY (ID_CONTRATO) REFERENCES CONTRATOS (ID_CONTRATO);
ALTER TABLE PERMISSOES ADD FOREIGN KEY (ID_PERFIL) REFERENCES PERFIS (ID_PERFIL);
ALTER TABLE USUARIOS ADD FOREIGN KEY (ID_PERFIL) REFERENCES PERFIS (ID_PERFIL);

/******************************************************************************/
/****                          Check constraints                           ****/
/******************************************************************************/


ALTER TABLE ATIVOS ADD CONSTRAINT INTEG_21 CHECK (status IN ('disponível', 'alugado', 'manutencao'));

ALTER TABLE CLIENTES ADD CONSTRAINT INTEG_16 CHECK (tipo_pessoa IN ('F', 'J'));

ALTER TABLE PAGAMENTOS ADD CONSTRAINT INTEG_39 CHECK (status_pagamento IN ('pendente', 'pago', 'atrasado'));


/******************************************************************************/
/****                               Indices                                ****/
/******************************************************************************/



/******************************************************************************/
/****                               Triggers                               ****/
/******************************************************************************/

SET TERM ^ ;

SET TERM ; ^

/******************************************************************************/
/****                              Procedures                              ****/
/******************************************************************************/

SET TERM ^ ;

SET TERM ; ^



/******************************************************************************/
/****                         Object descriptions                          ****/
/******************************************************************************/

